### ISSUE TITLE
Could not Start Pod

### ISSUE THREAD

**Issue by michelreek** [owncloud-docker/helm-charts#48]
Hello,

i could not start the owncloud deployment.
The Pod will not correctly start and i don'r really see an error.

the Pod Logs will only display:

```
3 Creating volume folders...
2 Creating hook folders...
1 Waiting for MySQL...
```
an the Pod will automatic terminated by the Readiness probe:
`Readiness probe failed: Get "http://xx.xx.x.xxx:8080/status.php": dial tcp xx.xx.x.xx:8080: connect: connection refused
`
the only values what i have changed are the following:

```
owncloud:
  adminPassword: "xxx"
  adminUsername: "xxx"
  db:
    fail: "true"
    host: "myhostname"
    name: "owncloud"
    password: "mypassword"
    prefix: "oc_"
    timeout: "30"
    type: "mysql"
    username: "owncloud"
  domain: "clouddomain"
  debug: true
  defaultLanguage: "de"

persistence:
  # -- Enables persistence.
  enabled: true
  owncloud:
    accessMode:
      - ReadWriteOnce
    size: 40Gi

ingress:
  enabled: true
  annotations: 
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
  tls: []
  #  - secretName: owncloud-tls
  #    hosts:
  #       - clouddomain
```

any idea where i have an typo or something ?

Kind Regards

**Comment by xoxys** [comment]
Is the db running external or on the same Kubernetes cluster? Hanging with `Waiting for MySQL`  means the DB can't be reached from the Pod.

**Comment by michelreek** [comment]
Thanks @xoxys...
On the Database Server was an Typo in the Firewall RuleSet.
