### ISSUE TITLE
NodeSelector don't work for cronjobs 

### ISSUE THREAD

**Issue by dominch** [owncloud-docker/helm-charts#52]
I started this helm with added: 
```
nodeSelector:
  kubernetes.io/hostname: hworker3
```
this deployed owncloud with pods running on this particular node, nodeSelector is added to deployments (and pods) correctly) 
but it's not for CronJobs, those were created on different nodes and failed to do anything (because of storage avaiablibity)

**Comment by xoxys** [comment]
Thanks for the report!
